version: "3.9"
services:
  server:
    container_name: server
    build: 
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    volumes:
      - ./src/core:/var/www/html
      - ./tools/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - core
  core:
    container_name: core
    build: 
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src/core:/var/www/html
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./envs/mysql.env
    ports:
      - 3306:3306